- name: Product 1
  image: /assets/images/product1.jpg
  price: $19.99
  description: "A great product for your needs."
- name: Product 2
  image: /assets/images/product2.jpg
  price: $29.99
  description: "Another fantastic item."
- name: Product 3
  image: /assets/images/product3.jpg
  price: $39.99
  description: "Top quality and value."
