
- name:  ספירלה פידג'ט
  slug: spiral-fidget
  image: https://media.printables.com/media/prints/1201199/images/9022078_1528e7db-92cf-427a-b93b-679704cd5a09_7072bbf3-e7fc-46f6-9a42-0f0ebba33ebb/thumbs/inside/1600x1200/jpeg/large_display_img_8444_1201199.webp
  price: ₪14.00
  description: ספירלת פידג'ט – כי לילדים בטח אין מספיק דרכים להעסיק את הידיים. לסובב, לסובב, ושוב לסובב. כיף בלי סוף (ואולי קצת שקט להורים).
- name: נחש מתפתל
  slug: flexible-snake
  image: https://media.printables.com/media/prints/1138614/images/8591534_d31e191d-f4eb-4b32-9a00-466e1cf4c819_b39025ef-5579-46e1-aa3c-fcb382a6068d/thumbs/inside/1920x1440/jpg/flexisnake_43_5.webp
  price: ₪12.00
  description: "Flexible articulated dragon, a favorite among 3D print enthusiasts. Photo: Printables user, CC BY."
- name: Geometric Planter
  slug: geometric-planter
  image: https://media.printables.com/media/prints/11098/images/112991_1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d/thumbs/cover/800x800/geometric-planter.jpg
  price: ₪12.00
  description: "Modern geometric planter for succulents and small plants. Photo: Printables user, CC BY."
- name: Phone Stand
  slug: phone-stand
  image: https://media.printables.com/media/prints/10047/images/101010_7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d/thumbs/cover/800x800/phone-stand.jpg
  price: ₪8.00
  description: "Handy 3D printed phone stand for desk or nightstand. Photo: Printables user, CC BY."
- name: Tool Holder
  slug: tool-holder 
  image: https://media.printables.com/media/prints/10048/images/101011_3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f/thumbs/cover/800x800/tool-holder.jpg
  price: ₪10.00
  description: "Organize your workspace with this 3D printed tool holder. Photo: Printables user, CC BY."
- name: Miniature Figurine
  slug: miniature-figurine
  image: https://media.printables.com/media/prints/10049/images/101012_5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b/thumbs/cover/800x800/miniature-figurine.jpg
  price: ₪18.00
  description: "Detailed 3D printed miniature figurine, great for collections. Photo: Printables user, CC BY."
